/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "arbitro2_synth.v:1" *)
module arbitro2_synth(clk, reset_L, data_in, fifo_empty, fifo0_almost_full, fifo1_almost_full, fifo2_almost_full, fifo3_almost_full, valid, data_out_synth, push0_synth, push1_synth, push2_synth, push3_synth, pop_synth, cont4_synth);
  (* src = "arbitro2_synth.v:66" *)
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  (* src = "arbitro2_synth.v:4" *)
  input clk;
  (* src = "arbitro2_synth.v:12" *)
  output [4:0] cont4_synth;
  (* src = "arbitro2_synth.v:5" *)
  input [11:0] data_in;
  (* src = "arbitro2_synth.v:9" *)
  output [11:0] data_out_synth;
  (* src = "arbitro2_synth.v:7" *)
  input fifo0_almost_full;
  (* src = "arbitro2_synth.v:7" *)
  input fifo1_almost_full;
  (* src = "arbitro2_synth.v:7" *)
  input fifo2_almost_full;
  (* src = "arbitro2_synth.v:7" *)
  input fifo3_almost_full;
  (* src = "arbitro2_synth.v:6" *)
  input fifo_empty;
  (* src = "arbitro2_synth.v:11" *)
  output pop_synth;
  (* src = "arbitro2_synth.v:10" *)
  output push0_synth;
  (* src = "arbitro2_synth.v:10" *)
  output push1_synth;
  (* src = "arbitro2_synth.v:10" *)
  output push2_synth;
  (* src = "arbitro2_synth.v:10" *)
  output push3_synth;
  (* src = "arbitro2_synth.v:4" *)
  input reset_L;
  (* src = "arbitro2_synth.v:8" *)
  input valid;
  NOT _044_ (
    .A(data_in[11]),
    .Y(_007_)
  );
  NOT _045_ (
    .A(fifo_empty),
    .Y(_008_)
  );
  NOT _046_ (
    .A(cont4_synth[1]),
    .Y(_009_)
  );
  NOT _047_ (
    .A(cont4_synth[2]),
    .Y(_010_)
  );
  NOT _048_ (
    .A(cont4_synth[4]),
    .Y(_011_)
  );
  NOT _049_ (
    .A(data_in[0]),
    .Y(_012_)
  );
  NOT _050_ (
    .A(data_in[1]),
    .Y(_013_)
  );
  NOT _051_ (
    .A(data_in[2]),
    .Y(_014_)
  );
  NOT _052_ (
    .A(data_in[3]),
    .Y(_015_)
  );
  NOT _053_ (
    .A(data_in[4]),
    .Y(_016_)
  );
  NOT _054_ (
    .A(data_in[5]),
    .Y(_017_)
  );
  NOT _055_ (
    .A(data_in[6]),
    .Y(_018_)
  );
  NOT _056_ (
    .A(data_in[7]),
    .Y(_019_)
  );
  NOT _057_ (
    .A(data_in[8]),
    .Y(_020_)
  );
  NOT _058_ (
    .A(data_in[9]),
    .Y(_021_)
  );
  NAND _059_ (
    .A(cont4_synth[0]),
    .B(valid),
    .Y(_022_)
  );
  NOT _060_ (
    .A(_022_),
    .Y(_023_)
  );
  NAND _061_ (
    .A(reset_L),
    .B(valid),
    .Y(_024_)
  );
  NOT _062_ (
    .A(_024_),
    .Y(_025_)
  );
  NOR _063_ (
    .A(cont4_synth[0]),
    .B(valid),
    .Y(_026_)
  );
  NAND _064_ (
    .A(reset_L),
    .B(_022_),
    .Y(_027_)
  );
  NOR _065_ (
    .A(_026_),
    .B(_027_),
    .Y(_000_[0])
  );
  NOR _066_ (
    .A(_009_),
    .B(_022_),
    .Y(_028_)
  );
  NAND _067_ (
    .A(cont4_synth[1]),
    .B(_023_),
    .Y(_029_)
  );
  NAND _068_ (
    .A(_009_),
    .B(_022_),
    .Y(_030_)
  );
  NAND _069_ (
    .A(reset_L),
    .B(_030_),
    .Y(_031_)
  );
  NOR _070_ (
    .A(_028_),
    .B(_031_),
    .Y(_000_[1])
  );
  NOR _071_ (
    .A(_010_),
    .B(_029_),
    .Y(_032_)
  );
  NAND _072_ (
    .A(_010_),
    .B(_029_),
    .Y(_033_)
  );
  NAND _073_ (
    .A(reset_L),
    .B(_033_),
    .Y(_034_)
  );
  NOR _074_ (
    .A(_032_),
    .B(_034_),
    .Y(_000_[2])
  );
  NAND _075_ (
    .A(cont4_synth[3]),
    .B(_032_),
    .Y(_035_)
  );
  NOT _076_ (
    .A(_035_),
    .Y(_036_)
  );
  NOR _077_ (
    .A(cont4_synth[3]),
    .B(_032_),
    .Y(_037_)
  );
  NOT _078_ (
    .A(_037_),
    .Y(_038_)
  );
  NAND _079_ (
    .A(reset_L),
    .B(_038_),
    .Y(_039_)
  );
  NOR _080_ (
    .A(_036_),
    .B(_039_),
    .Y(_000_[3])
  );
  NOR _081_ (
    .A(_011_),
    .B(_035_),
    .Y(_040_)
  );
  NAND _082_ (
    .A(_011_),
    .B(_035_),
    .Y(_041_)
  );
  NAND _083_ (
    .A(reset_L),
    .B(_041_),
    .Y(_042_)
  );
  NOR _084_ (
    .A(_040_),
    .B(_042_),
    .Y(_000_[4])
  );
  NOR _085_ (
    .A(_012_),
    .B(_024_),
    .Y(data_out_synth[0])
  );
  NOR _086_ (
    .A(_013_),
    .B(_024_),
    .Y(data_out_synth[1])
  );
  NOR _087_ (
    .A(_014_),
    .B(_024_),
    .Y(data_out_synth[2])
  );
  NOR _088_ (
    .A(_015_),
    .B(_024_),
    .Y(data_out_synth[3])
  );
  NOR _089_ (
    .A(_016_),
    .B(_024_),
    .Y(data_out_synth[4])
  );
  NOR _090_ (
    .A(_017_),
    .B(_024_),
    .Y(data_out_synth[5])
  );
  NOR _091_ (
    .A(_018_),
    .B(_024_),
    .Y(data_out_synth[6])
  );
  NOR _092_ (
    .A(_019_),
    .B(_024_),
    .Y(data_out_synth[7])
  );
  NOR _093_ (
    .A(_020_),
    .B(_024_),
    .Y(data_out_synth[8])
  );
  NOR _094_ (
    .A(_021_),
    .B(_024_),
    .Y(data_out_synth[9])
  );
  NAND _095_ (
    .A(data_in[10]),
    .B(_025_),
    .Y(_043_)
  );
  NOT _096_ (
    .A(_043_),
    .Y(data_out_synth[10])
  );
  NAND _097_ (
    .A(data_in[11]),
    .B(_025_),
    .Y(_001_)
  );
  NOT _098_ (
    .A(_001_),
    .Y(data_out_synth[11])
  );
  NOR _099_ (
    .A(_007_),
    .B(_043_),
    .Y(push3_synth)
  );
  NOR _100_ (
    .A(fifo0_almost_full),
    .B(fifo3_almost_full),
    .Y(_002_)
  );
  NAND _101_ (
    .A(_008_),
    .B(_002_),
    .Y(_003_)
  );
  NOR _102_ (
    .A(fifo1_almost_full),
    .B(fifo2_almost_full),
    .Y(_004_)
  );
  NAND _103_ (
    .A(reset_L),
    .B(_004_),
    .Y(_005_)
  );
  NOR _104_ (
    .A(_003_),
    .B(_005_),
    .Y(pop_synth)
  );
  NAND _105_ (
    .A(_007_),
    .B(_025_),
    .Y(_006_)
  );
  NOR _106_ (
    .A(data_in[10]),
    .B(_006_),
    .Y(push0_synth)
  );
  NOR _107_ (
    .A(data_in[10]),
    .B(_001_),
    .Y(push2_synth)
  );
  NOR _108_ (
    .A(data_in[11]),
    .B(_043_),
    .Y(push1_synth)
  );
  (* src = "arbitro2_synth.v:66" *)
  DFF _109_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cont4_synth[0])
  );
  (* src = "arbitro2_synth.v:66" *)
  DFF _110_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cont4_synth[1])
  );
  (* src = "arbitro2_synth.v:66" *)
  DFF _111_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cont4_synth[2])
  );
  (* src = "arbitro2_synth.v:66" *)
  DFF _112_ (
    .C(clk),
    .D(_000_[3]),
    .Q(cont4_synth[3])
  );
  (* src = "arbitro2_synth.v:66" *)
  DFF _113_ (
    .C(clk),
    .D(_000_[4]),
    .Q(cont4_synth[4])
  );
endmodule
