/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "arbitro2_synth.v:1" *)
module arbitro2_synth(clk, reset_L, data_in, fifo_empty, fifo0_almost_full, fifo1_almost_full, fifo2_almost_full, fifo3_almost_full, valid, data_out_synth, push0_synth, push1_synth, push2_synth, push3_synth, pop_synth, cont4_synth);
  (* src = "arbitro2_synth.v:66" *)
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  (* src = "arbitro2_synth.v:4" *)
  input clk;
  (* src = "arbitro2_synth.v:12" *)
  output [4:0] cont4_synth;
  (* src = "arbitro2_synth.v:5" *)
  input [11:0] data_in;
  (* src = "arbitro2_synth.v:9" *)
  output [11:0] data_out_synth;
  (* src = "arbitro2_synth.v:7" *)
  input fifo0_almost_full;
  (* src = "arbitro2_synth.v:7" *)
  input fifo1_almost_full;
  (* src = "arbitro2_synth.v:7" *)
  input fifo2_almost_full;
  (* src = "arbitro2_synth.v:7" *)
  input fifo3_almost_full;
  (* src = "arbitro2_synth.v:6" *)
  input fifo_empty;
  (* src = "arbitro2_synth.v:11" *)
  output pop_synth;
  (* src = "arbitro2_synth.v:10" *)
  output push0_synth;
  (* src = "arbitro2_synth.v:10" *)
  output push1_synth;
  (* src = "arbitro2_synth.v:10" *)
  output push2_synth;
  (* src = "arbitro2_synth.v:10" *)
  output push3_synth;
  (* src = "arbitro2_synth.v:4" *)
  input reset_L;
  (* src = "arbitro2_synth.v:8" *)
  input valid;
  NOR _049_ (
    .A(valid),
    .B(cont4_synth[0]),
    .Y(_011_)
  );
  NAND _050_ (
    .A(valid),
    .B(cont4_synth[0]),
    .Y(_012_)
  );
  NAND _051_ (
    .A(_012_),
    .B(reset_L),
    .Y(_013_)
  );
  NOR _052_ (
    .A(_013_),
    .B(_011_),
    .Y(_000_[0])
  );
  NOT _053_ (
    .A(cont4_synth[1]),
    .Y(_014_)
  );
  NOR _054_ (
    .A(_012_),
    .B(_014_),
    .Y(_015_)
  );
  NAND _055_ (
    .A(_012_),
    .B(_014_),
    .Y(_016_)
  );
  NAND _056_ (
    .A(_016_),
    .B(reset_L),
    .Y(_017_)
  );
  NOR _057_ (
    .A(_017_),
    .B(_015_),
    .Y(_000_[1])
  );
  NOT _058_ (
    .A(cont4_synth[2]),
    .Y(_018_)
  );
  NOT _059_ (
    .A(cont4_synth[0]),
    .Y(_019_)
  );
  NOT _060_ (
    .A(valid),
    .Y(_020_)
  );
  NOR _061_ (
    .A(_020_),
    .B(_019_),
    .Y(_021_)
  );
  NAND _062_ (
    .A(_021_),
    .B(cont4_synth[1]),
    .Y(_022_)
  );
  NOR _063_ (
    .A(_022_),
    .B(_018_),
    .Y(_023_)
  );
  NAND _064_ (
    .A(_022_),
    .B(_018_),
    .Y(_024_)
  );
  NAND _065_ (
    .A(_024_),
    .B(reset_L),
    .Y(_025_)
  );
  NOR _066_ (
    .A(_025_),
    .B(_023_),
    .Y(_000_[2])
  );
  NOT _067_ (
    .A(cont4_synth[3]),
    .Y(_026_)
  );
  NAND _068_ (
    .A(_015_),
    .B(cont4_synth[2]),
    .Y(_027_)
  );
  NOR _069_ (
    .A(_027_),
    .B(_026_),
    .Y(_028_)
  );
  NAND _070_ (
    .A(_027_),
    .B(_026_),
    .Y(_029_)
  );
  NAND _071_ (
    .A(_029_),
    .B(reset_L),
    .Y(_030_)
  );
  NOR _072_ (
    .A(_030_),
    .B(_028_),
    .Y(_000_[3])
  );
  NOT _073_ (
    .A(reset_L),
    .Y(_031_)
  );
  NOT _074_ (
    .A(cont4_synth[4]),
    .Y(_032_)
  );
  NOR _075_ (
    .A(_028_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _076_ (
    .A(_023_),
    .B(cont4_synth[3]),
    .Y(_034_)
  );
  NOR _077_ (
    .A(_034_),
    .B(cont4_synth[4]),
    .Y(_035_)
  );
  NOR _078_ (
    .A(_035_),
    .B(_033_),
    .Y(_036_)
  );
  NOR _079_ (
    .A(_036_),
    .B(_031_),
    .Y(_000_[4])
  );
  NOT _080_ (
    .A(data_in[0]),
    .Y(_037_)
  );
  NOR _081_ (
    .A(_031_),
    .B(_020_),
    .Y(_038_)
  );
  NOT _082_ (
    .A(_038_),
    .Y(_039_)
  );
  NOR _083_ (
    .A(_039_),
    .B(_037_),
    .Y(data_out_synth[0])
  );
  NOT _084_ (
    .A(data_in[1]),
    .Y(_040_)
  );
  NOR _085_ (
    .A(_039_),
    .B(_040_),
    .Y(data_out_synth[1])
  );
  NOT _086_ (
    .A(data_in[2]),
    .Y(_041_)
  );
  NOR _087_ (
    .A(_039_),
    .B(_041_),
    .Y(data_out_synth[2])
  );
  NOT _088_ (
    .A(data_in[3]),
    .Y(_042_)
  );
  NOR _089_ (
    .A(_039_),
    .B(_042_),
    .Y(data_out_synth[3])
  );
  NOT _090_ (
    .A(data_in[4]),
    .Y(_043_)
  );
  NOR _091_ (
    .A(_039_),
    .B(_043_),
    .Y(data_out_synth[4])
  );
  NOT _092_ (
    .A(data_in[5]),
    .Y(_044_)
  );
  NOR _093_ (
    .A(_039_),
    .B(_044_),
    .Y(data_out_synth[5])
  );
  NOT _094_ (
    .A(data_in[6]),
    .Y(_045_)
  );
  NOR _095_ (
    .A(_039_),
    .B(_045_),
    .Y(data_out_synth[6])
  );
  NOT _096_ (
    .A(data_in[7]),
    .Y(_046_)
  );
  NOR _097_ (
    .A(_039_),
    .B(_046_),
    .Y(data_out_synth[7])
  );
  NOT _098_ (
    .A(data_in[8]),
    .Y(_047_)
  );
  NOR _099_ (
    .A(_039_),
    .B(_047_),
    .Y(data_out_synth[8])
  );
  NOT _100_ (
    .A(data_in[9]),
    .Y(_048_)
  );
  NOR _101_ (
    .A(_039_),
    .B(_048_),
    .Y(data_out_synth[9])
  );
  NAND _102_ (
    .A(_038_),
    .B(data_in[10]),
    .Y(_001_)
  );
  NOT _103_ (
    .A(_001_),
    .Y(data_out_synth[10])
  );
  NAND _104_ (
    .A(_038_),
    .B(data_in[11]),
    .Y(_002_)
  );
  NOT _105_ (
    .A(_002_),
    .Y(data_out_synth[11])
  );
  NOT _106_ (
    .A(fifo_empty),
    .Y(_003_)
  );
  NOR _107_ (
    .A(fifo3_almost_full),
    .B(fifo0_almost_full),
    .Y(_004_)
  );
  NAND _108_ (
    .A(_004_),
    .B(_003_),
    .Y(_005_)
  );
  NOR _109_ (
    .A(fifo2_almost_full),
    .B(fifo1_almost_full),
    .Y(_006_)
  );
  NAND _110_ (
    .A(_006_),
    .B(reset_L),
    .Y(_007_)
  );
  NOR _111_ (
    .A(_007_),
    .B(_005_),
    .Y(pop_synth)
  );
  NOT _112_ (
    .A(data_in[10]),
    .Y(_008_)
  );
  NOR _113_ (
    .A(_002_),
    .B(_008_),
    .Y(push3_synth)
  );
  NOR _114_ (
    .A(_002_),
    .B(data_in[10]),
    .Y(push2_synth)
  );
  NOR _115_ (
    .A(_001_),
    .B(data_in[11]),
    .Y(push1_synth)
  );
  NOT _116_ (
    .A(data_in[11]),
    .Y(_009_)
  );
  NAND _117_ (
    .A(_009_),
    .B(_008_),
    .Y(_010_)
  );
  NOR _118_ (
    .A(_010_),
    .B(_039_),
    .Y(push0_synth)
  );
  DFF _119_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cont4_synth[0])
  );
  DFF _120_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cont4_synth[1])
  );
  DFF _121_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cont4_synth[2])
  );
  DFF _122_ (
    .C(clk),
    .D(_000_[3]),
    .Q(cont4_synth[3])
  );
  DFF _123_ (
    .C(clk),
    .D(_000_[4]),
    .Q(cont4_synth[4])
  );
endmodule
