/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "contador_synth.v:1" *)
module contador_synth(pop0, pop1, pop2, pop3, pop4, req, clk, reset_L, idle, idx, valid_synth, data_out_synth);
  (* src = "contador_synth.v:13" *)
  wire [4:0] _000_;
  (* src = "contador_synth.v:13" *)
  wire [4:0] _001_;
  (* src = "contador_synth.v:13" *)
  wire [4:0] _002_;
  (* src = "contador_synth.v:13" *)
  wire [4:0] _003_;
  (* src = "contador_synth.v:13" *)
  wire [4:0] _004_;
  (* src = "contador_synth.v:43" *)
  wire [4:0] _005_;
  (* src = "contador_synth.v:43" *)
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  (* src = "contador_synth.v:4" *)
  input clk;
  (* src = "contador_synth.v:10" *)
  wire [4:0] contador_synth_0;
  (* src = "contador_synth.v:10" *)
  wire [4:0] contador_synth_1;
  (* src = "contador_synth.v:10" *)
  wire [4:0] contador_synth_2;
  (* src = "contador_synth.v:10" *)
  wire [4:0] contador_synth_3;
  (* src = "contador_synth.v:10" *)
  wire [4:0] contador_synth_4;
  (* src = "contador_synth.v:7" *)
  output [4:0] data_out_synth;
  (* src = "contador_synth.v:4" *)
  input idle;
  (* src = "contador_synth.v:5" *)
  input [2:0] idx;
  (* src = "contador_synth.v:3" *)
  input pop0;
  (* src = "contador_synth.v:3" *)
  input pop1;
  (* src = "contador_synth.v:3" *)
  input pop2;
  (* src = "contador_synth.v:3" *)
  input pop3;
  (* src = "contador_synth.v:3" *)
  input pop4;
  (* src = "contador_synth.v:4" *)
  input req;
  (* src = "contador_synth.v:4" *)
  input reset_L;
  (* src = "contador_synth.v:6" *)
  output valid_synth;
  NOT _242_ (
    .A(idx[2]),
    .Y(_216_)
  );
  NOT _243_ (
    .A(idx[0]),
    .Y(_217_)
  );
  NOT _244_ (
    .A(idx[1]),
    .Y(_218_)
  );
  NOT _245_ (
    .A(contador_synth_0[1]),
    .Y(_219_)
  );
  NOT _246_ (
    .A(contador_synth_0[3]),
    .Y(_220_)
  );
  NOT _247_ (
    .A(contador_synth_0[4]),
    .Y(_221_)
  );
  NOT _248_ (
    .A(contador_synth_1[1]),
    .Y(_222_)
  );
  NOT _249_ (
    .A(contador_synth_1[3]),
    .Y(_223_)
  );
  NOT _250_ (
    .A(contador_synth_1[4]),
    .Y(_224_)
  );
  NOT _251_ (
    .A(contador_synth_2[0]),
    .Y(_225_)
  );
  NOT _252_ (
    .A(contador_synth_2[1]),
    .Y(_226_)
  );
  NOT _253_ (
    .A(contador_synth_2[2]),
    .Y(_227_)
  );
  NOT _254_ (
    .A(contador_synth_2[3]),
    .Y(_228_)
  );
  NOT _255_ (
    .A(contador_synth_2[4]),
    .Y(_229_)
  );
  NOT _256_ (
    .A(contador_synth_3[1]),
    .Y(_230_)
  );
  NOT _257_ (
    .A(contador_synth_3[3]),
    .Y(_231_)
  );
  NOT _258_ (
    .A(contador_synth_3[4]),
    .Y(_232_)
  );
  NOT _259_ (
    .A(contador_synth_4[1]),
    .Y(_233_)
  );
  NOT _260_ (
    .A(contador_synth_4[3]),
    .Y(_234_)
  );
  NOT _261_ (
    .A(contador_synth_4[4]),
    .Y(_235_)
  );
  NOT _262_ (
    .A(reset_L),
    .Y(_236_)
  );
  NOT _263_ (
    .A(valid_synth),
    .Y(_237_)
  );
  NAND _264_ (
    .A(idle),
    .B(req),
    .Y(_238_)
  );
  NOT _265_ (
    .A(_238_),
    .Y(_239_)
  );
  NAND _266_ (
    .A(data_out_synth[0]),
    .B(_238_),
    .Y(_240_)
  );
  NOT _267_ (
    .A(_240_),
    .Y(_241_)
  );
  NAND _268_ (
    .A(_216_),
    .B(_217_),
    .Y(_007_)
  );
  NOR _269_ (
    .A(_218_),
    .B(_007_),
    .Y(_008_)
  );
  NOR _270_ (
    .A(idx[2]),
    .B(_217_),
    .Y(_009_)
  );
  NAND _271_ (
    .A(_216_),
    .B(idx[0]),
    .Y(_010_)
  );
  NOR _272_ (
    .A(idx[1]),
    .B(_010_),
    .Y(_011_)
  );
  NAND _273_ (
    .A(_218_),
    .B(_009_),
    .Y(_012_)
  );
  NOR _274_ (
    .A(idx[0]),
    .B(idx[1]),
    .Y(_013_)
  );
  NOT _275_ (
    .A(_013_),
    .Y(_014_)
  );
  NOR _276_ (
    .A(idx[2]),
    .B(_014_),
    .Y(_015_)
  );
  NAND _277_ (
    .A(_216_),
    .B(_013_),
    .Y(_016_)
  );
  NOR _278_ (
    .A(data_out_synth[0]),
    .B(_015_),
    .Y(_017_)
  );
  NOR _279_ (
    .A(contador_synth_0[0]),
    .B(_016_),
    .Y(_018_)
  );
  NOR _280_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _281_ (
    .A(_011_),
    .B(_019_),
    .Y(_020_)
  );
  NOR _282_ (
    .A(contador_synth_1[0]),
    .B(_012_),
    .Y(_021_)
  );
  NOR _283_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _284_ (
    .A(_008_),
    .B(_022_),
    .Y(_023_)
  );
  NOR _285_ (
    .A(_218_),
    .B(_010_),
    .Y(_024_)
  );
  NAND _286_ (
    .A(idx[1]),
    .B(_009_),
    .Y(_025_)
  );
  NAND _287_ (
    .A(_225_),
    .B(_008_),
    .Y(_026_)
  );
  NAND _288_ (
    .A(_025_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _289_ (
    .A(_023_),
    .B(_027_),
    .Y(_028_)
  );
  NAND _290_ (
    .A(idx[2]),
    .B(_013_),
    .Y(_029_)
  );
  NAND _291_ (
    .A(contador_synth_3[0]),
    .B(_024_),
    .Y(_030_)
  );
  NAND _292_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _293_ (
    .A(_028_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _294_ (
    .A(contador_synth_4[0]),
    .B(_029_),
    .Y(_033_)
  );
  NOR _295_ (
    .A(_238_),
    .B(_033_),
    .Y(_034_)
  );
  NOT _296_ (
    .A(_034_),
    .Y(_035_)
  );
  NOR _297_ (
    .A(_032_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _298_ (
    .A(_241_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _299_ (
    .A(_236_),
    .B(_037_),
    .Y(_005_[0])
  );
  NAND _300_ (
    .A(data_out_synth[1]),
    .B(_238_),
    .Y(_038_)
  );
  NOT _301_ (
    .A(_038_),
    .Y(_039_)
  );
  NOR _302_ (
    .A(data_out_synth[1]),
    .B(_015_),
    .Y(_040_)
  );
  NOR _303_ (
    .A(contador_synth_0[1]),
    .B(_016_),
    .Y(_041_)
  );
  NOR _304_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _305_ (
    .A(_011_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _306_ (
    .A(contador_synth_1[1]),
    .B(_012_),
    .Y(_044_)
  );
  NOR _307_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _308_ (
    .A(_008_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _309_ (
    .A(_226_),
    .B(_008_),
    .Y(_047_)
  );
  NAND _310_ (
    .A(_025_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _311_ (
    .A(_046_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _312_ (
    .A(contador_synth_3[1]),
    .B(_024_),
    .Y(_050_)
  );
  NAND _313_ (
    .A(_029_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _314_ (
    .A(_049_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _315_ (
    .A(contador_synth_4[1]),
    .B(_029_),
    .Y(_053_)
  );
  NOR _316_ (
    .A(_238_),
    .B(_053_),
    .Y(_054_)
  );
  NOT _317_ (
    .A(_054_),
    .Y(_055_)
  );
  NOR _318_ (
    .A(_052_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _319_ (
    .A(_039_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _320_ (
    .A(_236_),
    .B(_057_),
    .Y(_005_[1])
  );
  NAND _321_ (
    .A(data_out_synth[2]),
    .B(_238_),
    .Y(_058_)
  );
  NOT _322_ (
    .A(_058_),
    .Y(_059_)
  );
  NOR _323_ (
    .A(data_out_synth[2]),
    .B(_015_),
    .Y(_060_)
  );
  NOR _324_ (
    .A(contador_synth_0[2]),
    .B(_016_),
    .Y(_061_)
  );
  NOR _325_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _326_ (
    .A(_011_),
    .B(_062_),
    .Y(_063_)
  );
  NOR _327_ (
    .A(contador_synth_1[2]),
    .B(_012_),
    .Y(_064_)
  );
  NOR _328_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _329_ (
    .A(_008_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _330_ (
    .A(_227_),
    .B(_008_),
    .Y(_067_)
  );
  NAND _331_ (
    .A(_025_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _332_ (
    .A(_066_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _333_ (
    .A(contador_synth_3[2]),
    .B(_024_),
    .Y(_070_)
  );
  NAND _334_ (
    .A(_029_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _335_ (
    .A(_069_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _336_ (
    .A(contador_synth_4[2]),
    .B(_029_),
    .Y(_073_)
  );
  NOR _337_ (
    .A(_238_),
    .B(_073_),
    .Y(_074_)
  );
  NOT _338_ (
    .A(_074_),
    .Y(_075_)
  );
  NOR _339_ (
    .A(_072_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _340_ (
    .A(_059_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _341_ (
    .A(_236_),
    .B(_077_),
    .Y(_005_[2])
  );
  NAND _342_ (
    .A(data_out_synth[3]),
    .B(_238_),
    .Y(_078_)
  );
  NOT _343_ (
    .A(_078_),
    .Y(_079_)
  );
  NOR _344_ (
    .A(_220_),
    .B(_016_),
    .Y(_080_)
  );
  NAND _345_ (
    .A(data_out_synth[3]),
    .B(_016_),
    .Y(_081_)
  );
  NAND _346_ (
    .A(_012_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _347_ (
    .A(_080_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _348_ (
    .A(contador_synth_1[3]),
    .B(_012_),
    .Y(_084_)
  );
  NOR _349_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _350_ (
    .A(_008_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _351_ (
    .A(_228_),
    .B(_008_),
    .Y(_087_)
  );
  NAND _352_ (
    .A(_025_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _353_ (
    .A(_086_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _354_ (
    .A(contador_synth_3[3]),
    .B(_024_),
    .Y(_090_)
  );
  NAND _355_ (
    .A(_029_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _356_ (
    .A(_089_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _357_ (
    .A(contador_synth_4[3]),
    .B(_029_),
    .Y(_093_)
  );
  NOR _358_ (
    .A(_238_),
    .B(_093_),
    .Y(_094_)
  );
  NOT _359_ (
    .A(_094_),
    .Y(_095_)
  );
  NOR _360_ (
    .A(_092_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _361_ (
    .A(_079_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _362_ (
    .A(_236_),
    .B(_097_),
    .Y(_005_[3])
  );
  NAND _363_ (
    .A(data_out_synth[4]),
    .B(_238_),
    .Y(_098_)
  );
  NOT _364_ (
    .A(_098_),
    .Y(_099_)
  );
  NOR _365_ (
    .A(data_out_synth[4]),
    .B(_015_),
    .Y(_100_)
  );
  NOR _366_ (
    .A(contador_synth_0[4]),
    .B(_016_),
    .Y(_101_)
  );
  NOR _367_ (
    .A(_100_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _368_ (
    .A(_011_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _369_ (
    .A(contador_synth_1[4]),
    .B(_012_),
    .Y(_104_)
  );
  NOR _370_ (
    .A(_103_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _371_ (
    .A(_008_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _372_ (
    .A(_229_),
    .B(_008_),
    .Y(_107_)
  );
  NAND _373_ (
    .A(_025_),
    .B(_107_),
    .Y(_108_)
  );
  NOR _374_ (
    .A(_106_),
    .B(_108_),
    .Y(_109_)
  );
  NAND _375_ (
    .A(contador_synth_3[4]),
    .B(_024_),
    .Y(_110_)
  );
  NAND _376_ (
    .A(_029_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _377_ (
    .A(_109_),
    .B(_111_),
    .Y(_112_)
  );
  NOR _378_ (
    .A(contador_synth_4[4]),
    .B(_029_),
    .Y(_113_)
  );
  NOR _379_ (
    .A(_238_),
    .B(_113_),
    .Y(_114_)
  );
  NOT _380_ (
    .A(_114_),
    .Y(_115_)
  );
  NOR _381_ (
    .A(_112_),
    .B(_115_),
    .Y(_116_)
  );
  NOR _382_ (
    .A(_099_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _383_ (
    .A(_236_),
    .B(_117_),
    .Y(_005_[4])
  );
  NAND _384_ (
    .A(idx[2]),
    .B(_237_),
    .Y(_118_)
  );
  NOR _385_ (
    .A(_013_),
    .B(_118_),
    .Y(_119_)
  );
  NAND _386_ (
    .A(reset_L),
    .B(_239_),
    .Y(_120_)
  );
  NOR _387_ (
    .A(_119_),
    .B(_120_),
    .Y(_006_)
  );
  NAND _388_ (
    .A(contador_synth_4[0]),
    .B(pop4),
    .Y(_121_)
  );
  NOT _389_ (
    .A(_121_),
    .Y(_122_)
  );
  NOR _390_ (
    .A(contador_synth_4[0]),
    .B(pop4),
    .Y(_123_)
  );
  NOT _391_ (
    .A(_123_),
    .Y(_124_)
  );
  NAND _392_ (
    .A(reset_L),
    .B(_124_),
    .Y(_125_)
  );
  NOR _393_ (
    .A(_122_),
    .B(_125_),
    .Y(_004_[0])
  );
  NOR _394_ (
    .A(_233_),
    .B(_121_),
    .Y(_126_)
  );
  NAND _395_ (
    .A(_233_),
    .B(_121_),
    .Y(_127_)
  );
  NAND _396_ (
    .A(reset_L),
    .B(_127_),
    .Y(_128_)
  );
  NOR _397_ (
    .A(_126_),
    .B(_128_),
    .Y(_004_[1])
  );
  NAND _398_ (
    .A(contador_synth_4[2]),
    .B(_126_),
    .Y(_129_)
  );
  NOT _399_ (
    .A(_129_),
    .Y(_130_)
  );
  NOR _400_ (
    .A(contador_synth_4[2]),
    .B(_126_),
    .Y(_131_)
  );
  NAND _401_ (
    .A(reset_L),
    .B(_129_),
    .Y(_132_)
  );
  NOR _402_ (
    .A(_131_),
    .B(_132_),
    .Y(_004_[2])
  );
  NAND _403_ (
    .A(contador_synth_4[3]),
    .B(_130_),
    .Y(_133_)
  );
  NOT _404_ (
    .A(_133_),
    .Y(_134_)
  );
  NAND _405_ (
    .A(_234_),
    .B(_129_),
    .Y(_135_)
  );
  NAND _406_ (
    .A(reset_L),
    .B(_135_),
    .Y(_136_)
  );
  NOR _407_ (
    .A(_134_),
    .B(_136_),
    .Y(_004_[3])
  );
  NOR _408_ (
    .A(_235_),
    .B(_133_),
    .Y(_137_)
  );
  NAND _409_ (
    .A(_235_),
    .B(_133_),
    .Y(_138_)
  );
  NAND _410_ (
    .A(reset_L),
    .B(_138_),
    .Y(_139_)
  );
  NOR _411_ (
    .A(_137_),
    .B(_139_),
    .Y(_004_[4])
  );
  NAND _412_ (
    .A(contador_synth_3[0]),
    .B(pop3),
    .Y(_140_)
  );
  NOT _413_ (
    .A(_140_),
    .Y(_141_)
  );
  NOR _414_ (
    .A(contador_synth_3[0]),
    .B(pop3),
    .Y(_142_)
  );
  NOT _415_ (
    .A(_142_),
    .Y(_143_)
  );
  NAND _416_ (
    .A(reset_L),
    .B(_143_),
    .Y(_144_)
  );
  NOR _417_ (
    .A(_141_),
    .B(_144_),
    .Y(_003_[0])
  );
  NOR _418_ (
    .A(_230_),
    .B(_140_),
    .Y(_145_)
  );
  NAND _419_ (
    .A(_230_),
    .B(_140_),
    .Y(_146_)
  );
  NAND _420_ (
    .A(reset_L),
    .B(_146_),
    .Y(_147_)
  );
  NOR _421_ (
    .A(_145_),
    .B(_147_),
    .Y(_003_[1])
  );
  NAND _422_ (
    .A(contador_synth_3[2]),
    .B(_145_),
    .Y(_148_)
  );
  NOT _423_ (
    .A(_148_),
    .Y(_149_)
  );
  NOR _424_ (
    .A(contador_synth_3[2]),
    .B(_145_),
    .Y(_150_)
  );
  NAND _425_ (
    .A(reset_L),
    .B(_148_),
    .Y(_151_)
  );
  NOR _426_ (
    .A(_150_),
    .B(_151_),
    .Y(_003_[2])
  );
  NAND _427_ (
    .A(contador_synth_3[3]),
    .B(_149_),
    .Y(_152_)
  );
  NOT _428_ (
    .A(_152_),
    .Y(_153_)
  );
  NAND _429_ (
    .A(_231_),
    .B(_148_),
    .Y(_154_)
  );
  NAND _430_ (
    .A(reset_L),
    .B(_154_),
    .Y(_155_)
  );
  NOR _431_ (
    .A(_153_),
    .B(_155_),
    .Y(_003_[3])
  );
  NOR _432_ (
    .A(_232_),
    .B(_152_),
    .Y(_156_)
  );
  NAND _433_ (
    .A(_232_),
    .B(_152_),
    .Y(_157_)
  );
  NAND _434_ (
    .A(reset_L),
    .B(_157_),
    .Y(_158_)
  );
  NOR _435_ (
    .A(_156_),
    .B(_158_),
    .Y(_003_[4])
  );
  NAND _436_ (
    .A(contador_synth_2[0]),
    .B(pop2),
    .Y(_159_)
  );
  NOT _437_ (
    .A(_159_),
    .Y(_160_)
  );
  NOR _438_ (
    .A(contador_synth_2[0]),
    .B(pop2),
    .Y(_161_)
  );
  NOT _439_ (
    .A(_161_),
    .Y(_162_)
  );
  NAND _440_ (
    .A(reset_L),
    .B(_162_),
    .Y(_163_)
  );
  NOR _441_ (
    .A(_160_),
    .B(_163_),
    .Y(_002_[0])
  );
  NOR _442_ (
    .A(_226_),
    .B(_159_),
    .Y(_164_)
  );
  NAND _443_ (
    .A(_226_),
    .B(_159_),
    .Y(_165_)
  );
  NAND _444_ (
    .A(reset_L),
    .B(_165_),
    .Y(_166_)
  );
  NOR _445_ (
    .A(_164_),
    .B(_166_),
    .Y(_002_[1])
  );
  NAND _446_ (
    .A(contador_synth_2[2]),
    .B(_164_),
    .Y(_167_)
  );
  NOT _447_ (
    .A(_167_),
    .Y(_168_)
  );
  NOR _448_ (
    .A(contador_synth_2[2]),
    .B(_164_),
    .Y(_169_)
  );
  NAND _449_ (
    .A(reset_L),
    .B(_167_),
    .Y(_170_)
  );
  NOR _450_ (
    .A(_169_),
    .B(_170_),
    .Y(_002_[2])
  );
  NAND _451_ (
    .A(contador_synth_2[3]),
    .B(_168_),
    .Y(_171_)
  );
  NOT _452_ (
    .A(_171_),
    .Y(_172_)
  );
  NAND _453_ (
    .A(_228_),
    .B(_167_),
    .Y(_173_)
  );
  NAND _454_ (
    .A(reset_L),
    .B(_173_),
    .Y(_174_)
  );
  NOR _455_ (
    .A(_172_),
    .B(_174_),
    .Y(_002_[3])
  );
  NOR _456_ (
    .A(_229_),
    .B(_171_),
    .Y(_175_)
  );
  NAND _457_ (
    .A(_229_),
    .B(_171_),
    .Y(_176_)
  );
  NAND _458_ (
    .A(reset_L),
    .B(_176_),
    .Y(_177_)
  );
  NOR _459_ (
    .A(_175_),
    .B(_177_),
    .Y(_002_[4])
  );
  NAND _460_ (
    .A(contador_synth_1[0]),
    .B(pop1),
    .Y(_178_)
  );
  NOT _461_ (
    .A(_178_),
    .Y(_179_)
  );
  NOR _462_ (
    .A(contador_synth_1[0]),
    .B(pop1),
    .Y(_180_)
  );
  NOT _463_ (
    .A(_180_),
    .Y(_181_)
  );
  NAND _464_ (
    .A(reset_L),
    .B(_181_),
    .Y(_182_)
  );
  NOR _465_ (
    .A(_179_),
    .B(_182_),
    .Y(_001_[0])
  );
  NOR _466_ (
    .A(_222_),
    .B(_178_),
    .Y(_183_)
  );
  NAND _467_ (
    .A(_222_),
    .B(_178_),
    .Y(_184_)
  );
  NAND _468_ (
    .A(reset_L),
    .B(_184_),
    .Y(_185_)
  );
  NOR _469_ (
    .A(_183_),
    .B(_185_),
    .Y(_001_[1])
  );
  NAND _470_ (
    .A(contador_synth_1[2]),
    .B(_183_),
    .Y(_186_)
  );
  NOT _471_ (
    .A(_186_),
    .Y(_187_)
  );
  NOR _472_ (
    .A(contador_synth_1[2]),
    .B(_183_),
    .Y(_188_)
  );
  NAND _473_ (
    .A(reset_L),
    .B(_186_),
    .Y(_189_)
  );
  NOR _474_ (
    .A(_188_),
    .B(_189_),
    .Y(_001_[2])
  );
  NAND _475_ (
    .A(contador_synth_1[3]),
    .B(_187_),
    .Y(_190_)
  );
  NOT _476_ (
    .A(_190_),
    .Y(_191_)
  );
  NAND _477_ (
    .A(_223_),
    .B(_186_),
    .Y(_192_)
  );
  NAND _478_ (
    .A(reset_L),
    .B(_192_),
    .Y(_193_)
  );
  NOR _479_ (
    .A(_191_),
    .B(_193_),
    .Y(_001_[3])
  );
  NOR _480_ (
    .A(_224_),
    .B(_190_),
    .Y(_194_)
  );
  NAND _481_ (
    .A(_224_),
    .B(_190_),
    .Y(_195_)
  );
  NAND _482_ (
    .A(reset_L),
    .B(_195_),
    .Y(_196_)
  );
  NOR _483_ (
    .A(_194_),
    .B(_196_),
    .Y(_001_[4])
  );
  NAND _484_ (
    .A(contador_synth_0[0]),
    .B(pop0),
    .Y(_197_)
  );
  NOT _485_ (
    .A(_197_),
    .Y(_198_)
  );
  NOR _486_ (
    .A(contador_synth_0[0]),
    .B(pop0),
    .Y(_199_)
  );
  NOT _487_ (
    .A(_199_),
    .Y(_200_)
  );
  NAND _488_ (
    .A(reset_L),
    .B(_200_),
    .Y(_201_)
  );
  NOR _489_ (
    .A(_198_),
    .B(_201_),
    .Y(_000_[0])
  );
  NOR _490_ (
    .A(_219_),
    .B(_197_),
    .Y(_202_)
  );
  NAND _491_ (
    .A(_219_),
    .B(_197_),
    .Y(_203_)
  );
  NAND _492_ (
    .A(reset_L),
    .B(_203_),
    .Y(_204_)
  );
  NOR _493_ (
    .A(_202_),
    .B(_204_),
    .Y(_000_[1])
  );
  NAND _494_ (
    .A(contador_synth_0[2]),
    .B(_202_),
    .Y(_205_)
  );
  NOT _495_ (
    .A(_205_),
    .Y(_206_)
  );
  NOR _496_ (
    .A(contador_synth_0[2]),
    .B(_202_),
    .Y(_207_)
  );
  NAND _497_ (
    .A(reset_L),
    .B(_205_),
    .Y(_208_)
  );
  NOR _498_ (
    .A(_207_),
    .B(_208_),
    .Y(_000_[2])
  );
  NAND _499_ (
    .A(contador_synth_0[3]),
    .B(_206_),
    .Y(_209_)
  );
  NOT _500_ (
    .A(_209_),
    .Y(_210_)
  );
  NAND _501_ (
    .A(_220_),
    .B(_205_),
    .Y(_211_)
  );
  NAND _502_ (
    .A(reset_L),
    .B(_211_),
    .Y(_212_)
  );
  NOR _503_ (
    .A(_210_),
    .B(_212_),
    .Y(_000_[3])
  );
  NOR _504_ (
    .A(_221_),
    .B(_209_),
    .Y(_213_)
  );
  NAND _505_ (
    .A(_221_),
    .B(_209_),
    .Y(_214_)
  );
  NAND _506_ (
    .A(reset_L),
    .B(_214_),
    .Y(_215_)
  );
  NOR _507_ (
    .A(_213_),
    .B(_215_),
    .Y(_000_[4])
  );
  (* src = "contador_synth.v:43" *)
  DFF _508_ (
    .C(clk),
    .D(_006_),
    .Q(valid_synth)
  );
  (* src = "contador_synth.v:43" *)
  DFF _509_ (
    .C(clk),
    .D(_005_[0]),
    .Q(data_out_synth[0])
  );
  (* src = "contador_synth.v:43" *)
  DFF _510_ (
    .C(clk),
    .D(_005_[1]),
    .Q(data_out_synth[1])
  );
  (* src = "contador_synth.v:43" *)
  DFF _511_ (
    .C(clk),
    .D(_005_[2]),
    .Q(data_out_synth[2])
  );
  (* src = "contador_synth.v:43" *)
  DFF _512_ (
    .C(clk),
    .D(_005_[3]),
    .Q(data_out_synth[3])
  );
  (* src = "contador_synth.v:43" *)
  DFF _513_ (
    .C(clk),
    .D(_005_[4]),
    .Q(data_out_synth[4])
  );
  (* src = "contador_synth.v:13" *)
  DFF _514_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contador_synth_0[0])
  );
  (* src = "contador_synth.v:13" *)
  DFF _515_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contador_synth_0[1])
  );
  (* src = "contador_synth.v:13" *)
  DFF _516_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contador_synth_0[2])
  );
  (* src = "contador_synth.v:13" *)
  DFF _517_ (
    .C(clk),
    .D(_000_[3]),
    .Q(contador_synth_0[3])
  );
  (* src = "contador_synth.v:13" *)
  DFF _518_ (
    .C(clk),
    .D(_000_[4]),
    .Q(contador_synth_0[4])
  );
  (* src = "contador_synth.v:13" *)
  DFF _519_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contador_synth_1[0])
  );
  (* src = "contador_synth.v:13" *)
  DFF _520_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contador_synth_1[1])
  );
  (* src = "contador_synth.v:13" *)
  DFF _521_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contador_synth_1[2])
  );
  (* src = "contador_synth.v:13" *)
  DFF _522_ (
    .C(clk),
    .D(_001_[3]),
    .Q(contador_synth_1[3])
  );
  (* src = "contador_synth.v:13" *)
  DFF _523_ (
    .C(clk),
    .D(_001_[4]),
    .Q(contador_synth_1[4])
  );
  (* src = "contador_synth.v:13" *)
  DFF _524_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contador_synth_2[0])
  );
  (* src = "contador_synth.v:13" *)
  DFF _525_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contador_synth_2[1])
  );
  (* src = "contador_synth.v:13" *)
  DFF _526_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contador_synth_2[2])
  );
  (* src = "contador_synth.v:13" *)
  DFF _527_ (
    .C(clk),
    .D(_002_[3]),
    .Q(contador_synth_2[3])
  );
  (* src = "contador_synth.v:13" *)
  DFF _528_ (
    .C(clk),
    .D(_002_[4]),
    .Q(contador_synth_2[4])
  );
  (* src = "contador_synth.v:13" *)
  DFF _529_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contador_synth_3[0])
  );
  (* src = "contador_synth.v:13" *)
  DFF _530_ (
    .C(clk),
    .D(_003_[1]),
    .Q(contador_synth_3[1])
  );
  (* src = "contador_synth.v:13" *)
  DFF _531_ (
    .C(clk),
    .D(_003_[2]),
    .Q(contador_synth_3[2])
  );
  (* src = "contador_synth.v:13" *)
  DFF _532_ (
    .C(clk),
    .D(_003_[3]),
    .Q(contador_synth_3[3])
  );
  (* src = "contador_synth.v:13" *)
  DFF _533_ (
    .C(clk),
    .D(_003_[4]),
    .Q(contador_synth_3[4])
  );
  (* src = "contador_synth.v:13" *)
  DFF _534_ (
    .C(clk),
    .D(_004_[0]),
    .Q(contador_synth_4[0])
  );
  (* src = "contador_synth.v:13" *)
  DFF _535_ (
    .C(clk),
    .D(_004_[1]),
    .Q(contador_synth_4[1])
  );
  (* src = "contador_synth.v:13" *)
  DFF _536_ (
    .C(clk),
    .D(_004_[2]),
    .Q(contador_synth_4[2])
  );
  (* src = "contador_synth.v:13" *)
  DFF _537_ (
    .C(clk),
    .D(_004_[3]),
    .Q(contador_synth_4[3])
  );
  (* src = "contador_synth.v:13" *)
  DFF _538_ (
    .C(clk),
    .D(_004_[4]),
    .Q(contador_synth_4[4])
  );
endmodule
