/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "demux_4x1_synth.v:1" *)
module demux_4x1_synth(clk, reset_L, data_in0, data_in1, data_in2, data_in3, valid0, valid1, valid2, valid3, data_out_synth_mux);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  (* src = "demux_4x1_synth.v:4" *)
  input clk;
  (* src = "demux_4x1_synth.v:5" *)
  input [11:0] data_in0;
  (* src = "demux_4x1_synth.v:5" *)
  input [11:0] data_in1;
  (* src = "demux_4x1_synth.v:5" *)
  input [11:0] data_in2;
  (* src = "demux_4x1_synth.v:5" *)
  input [11:0] data_in3;
  (* src = "demux_4x1_synth.v:7" *)
  output [11:0] data_out_synth_mux;
  (* src = "demux_4x1_synth.v:4" *)
  input reset_L;
  (* src = "demux_4x1_synth.v:6" *)
  input valid0;
  (* src = "demux_4x1_synth.v:6" *)
  input valid1;
  (* src = "demux_4x1_synth.v:6" *)
  input valid2;
  (* src = "demux_4x1_synth.v:6" *)
  input valid3;
  NOT _147_ (
    .A(data_in0[2]),
    .Y(_113_)
  );
  NOT _148_ (
    .A(data_in0[3]),
    .Y(_114_)
  );
  NOT _149_ (
    .A(data_in0[4]),
    .Y(_115_)
  );
  NOT _150_ (
    .A(data_in0[5]),
    .Y(_116_)
  );
  NOT _151_ (
    .A(data_in0[6]),
    .Y(_117_)
  );
  NOT _152_ (
    .A(data_in0[7]),
    .Y(_118_)
  );
  NOT _153_ (
    .A(data_in0[8]),
    .Y(_119_)
  );
  NOT _154_ (
    .A(data_in0[9]),
    .Y(_120_)
  );
  NOT _155_ (
    .A(data_in0[10]),
    .Y(_121_)
  );
  NOT _156_ (
    .A(data_in0[11]),
    .Y(_122_)
  );
  NOT _157_ (
    .A(valid1),
    .Y(_123_)
  );
  NOT _158_ (
    .A(data_in3[0]),
    .Y(_124_)
  );
  NOT _159_ (
    .A(valid3),
    .Y(_125_)
  );
  NOT _160_ (
    .A(data_in3[1]),
    .Y(_126_)
  );
  NOT _161_ (
    .A(data_in3[2]),
    .Y(_127_)
  );
  NOT _162_ (
    .A(data_in3[3]),
    .Y(_128_)
  );
  NOT _163_ (
    .A(data_in3[4]),
    .Y(_129_)
  );
  NOT _164_ (
    .A(data_in3[5]),
    .Y(_130_)
  );
  NOT _165_ (
    .A(data_in3[6]),
    .Y(_131_)
  );
  NOT _166_ (
    .A(data_in3[7]),
    .Y(_132_)
  );
  NOT _167_ (
    .A(data_in3[8]),
    .Y(_133_)
  );
  NOT _168_ (
    .A(data_in3[9]),
    .Y(_134_)
  );
  NOT _169_ (
    .A(data_in3[10]),
    .Y(_135_)
  );
  NOT _170_ (
    .A(data_in3[11]),
    .Y(_136_)
  );
  NOT _171_ (
    .A(data_in0[0]),
    .Y(_137_)
  );
  NOT _172_ (
    .A(data_in0[1]),
    .Y(_138_)
  );
  NAND _173_ (
    .A(valid0),
    .B(_123_),
    .Y(_139_)
  );
  NOR _174_ (
    .A(_137_),
    .B(_139_),
    .Y(_140_)
  );
  NAND _175_ (
    .A(data_in1[0]),
    .B(valid1),
    .Y(_141_)
  );
  NOT _176_ (
    .A(_141_),
    .Y(_142_)
  );
  NOR _177_ (
    .A(_140_),
    .B(_142_),
    .Y(_143_)
  );
  NOR _178_ (
    .A(valid2),
    .B(_143_),
    .Y(_144_)
  );
  NAND _179_ (
    .A(data_in2[0]),
    .B(valid2),
    .Y(_145_)
  );
  NAND _180_ (
    .A(_125_),
    .B(_145_),
    .Y(_146_)
  );
  NOR _181_ (
    .A(_144_),
    .B(_146_),
    .Y(_000_)
  );
  NAND _182_ (
    .A(_124_),
    .B(valid3),
    .Y(_001_)
  );
  NAND _183_ (
    .A(reset_L),
    .B(_001_),
    .Y(_002_)
  );
  NOR _184_ (
    .A(_000_),
    .B(_002_),
    .Y(data_out_synth_mux[0])
  );
  NOR _185_ (
    .A(_138_),
    .B(_139_),
    .Y(_003_)
  );
  NAND _186_ (
    .A(valid1),
    .B(data_in1[1]),
    .Y(_004_)
  );
  NOT _187_ (
    .A(_004_),
    .Y(_005_)
  );
  NOR _188_ (
    .A(_003_),
    .B(_005_),
    .Y(_006_)
  );
  NOR _189_ (
    .A(valid2),
    .B(_006_),
    .Y(_007_)
  );
  NAND _190_ (
    .A(valid2),
    .B(data_in2[1]),
    .Y(_008_)
  );
  NAND _191_ (
    .A(_125_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _192_ (
    .A(_007_),
    .B(_009_),
    .Y(_010_)
  );
  NAND _193_ (
    .A(valid3),
    .B(_126_),
    .Y(_011_)
  );
  NAND _194_ (
    .A(reset_L),
    .B(_011_),
    .Y(_012_)
  );
  NOR _195_ (
    .A(_010_),
    .B(_012_),
    .Y(data_out_synth_mux[1])
  );
  NOR _196_ (
    .A(_113_),
    .B(_139_),
    .Y(_013_)
  );
  NAND _197_ (
    .A(valid1),
    .B(data_in1[2]),
    .Y(_014_)
  );
  NOT _198_ (
    .A(_014_),
    .Y(_015_)
  );
  NOR _199_ (
    .A(_013_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _200_ (
    .A(valid2),
    .B(_016_),
    .Y(_017_)
  );
  NAND _201_ (
    .A(valid2),
    .B(data_in2[2]),
    .Y(_018_)
  );
  NAND _202_ (
    .A(_125_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _203_ (
    .A(_017_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _204_ (
    .A(valid3),
    .B(_127_),
    .Y(_021_)
  );
  NAND _205_ (
    .A(reset_L),
    .B(_021_),
    .Y(_022_)
  );
  NOR _206_ (
    .A(_020_),
    .B(_022_),
    .Y(data_out_synth_mux[2])
  );
  NOR _207_ (
    .A(_114_),
    .B(_139_),
    .Y(_023_)
  );
  NAND _208_ (
    .A(valid1),
    .B(data_in1[3]),
    .Y(_024_)
  );
  NOT _209_ (
    .A(_024_),
    .Y(_025_)
  );
  NOR _210_ (
    .A(_023_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _211_ (
    .A(valid2),
    .B(_026_),
    .Y(_027_)
  );
  NAND _212_ (
    .A(valid2),
    .B(data_in2[3]),
    .Y(_028_)
  );
  NAND _213_ (
    .A(_125_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _214_ (
    .A(_027_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _215_ (
    .A(valid3),
    .B(_128_),
    .Y(_031_)
  );
  NAND _216_ (
    .A(reset_L),
    .B(_031_),
    .Y(_032_)
  );
  NOR _217_ (
    .A(_030_),
    .B(_032_),
    .Y(data_out_synth_mux[3])
  );
  NOR _218_ (
    .A(_115_),
    .B(_139_),
    .Y(_033_)
  );
  NAND _219_ (
    .A(valid1),
    .B(data_in1[4]),
    .Y(_034_)
  );
  NOT _220_ (
    .A(_034_),
    .Y(_035_)
  );
  NOR _221_ (
    .A(_033_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _222_ (
    .A(valid2),
    .B(_036_),
    .Y(_037_)
  );
  NAND _223_ (
    .A(valid2),
    .B(data_in2[4]),
    .Y(_038_)
  );
  NAND _224_ (
    .A(_125_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _225_ (
    .A(_037_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _226_ (
    .A(valid3),
    .B(_129_),
    .Y(_041_)
  );
  NAND _227_ (
    .A(reset_L),
    .B(_041_),
    .Y(_042_)
  );
  NOR _228_ (
    .A(_040_),
    .B(_042_),
    .Y(data_out_synth_mux[4])
  );
  NOR _229_ (
    .A(_116_),
    .B(_139_),
    .Y(_043_)
  );
  NAND _230_ (
    .A(valid1),
    .B(data_in1[5]),
    .Y(_044_)
  );
  NOT _231_ (
    .A(_044_),
    .Y(_045_)
  );
  NOR _232_ (
    .A(_043_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _233_ (
    .A(valid2),
    .B(_046_),
    .Y(_047_)
  );
  NAND _234_ (
    .A(valid2),
    .B(data_in2[5]),
    .Y(_048_)
  );
  NAND _235_ (
    .A(_125_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _236_ (
    .A(_047_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _237_ (
    .A(valid3),
    .B(_130_),
    .Y(_051_)
  );
  NAND _238_ (
    .A(reset_L),
    .B(_051_),
    .Y(_052_)
  );
  NOR _239_ (
    .A(_050_),
    .B(_052_),
    .Y(data_out_synth_mux[5])
  );
  NOR _240_ (
    .A(_117_),
    .B(_139_),
    .Y(_053_)
  );
  NAND _241_ (
    .A(valid1),
    .B(data_in1[6]),
    .Y(_054_)
  );
  NOT _242_ (
    .A(_054_),
    .Y(_055_)
  );
  NOR _243_ (
    .A(_053_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _244_ (
    .A(valid2),
    .B(_056_),
    .Y(_057_)
  );
  NAND _245_ (
    .A(valid2),
    .B(data_in2[6]),
    .Y(_058_)
  );
  NAND _246_ (
    .A(_125_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _247_ (
    .A(_057_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _248_ (
    .A(valid3),
    .B(_131_),
    .Y(_061_)
  );
  NAND _249_ (
    .A(reset_L),
    .B(_061_),
    .Y(_062_)
  );
  NOR _250_ (
    .A(_060_),
    .B(_062_),
    .Y(data_out_synth_mux[6])
  );
  NOR _251_ (
    .A(_118_),
    .B(_139_),
    .Y(_063_)
  );
  NAND _252_ (
    .A(valid1),
    .B(data_in1[7]),
    .Y(_064_)
  );
  NOT _253_ (
    .A(_064_),
    .Y(_065_)
  );
  NOR _254_ (
    .A(_063_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _255_ (
    .A(valid2),
    .B(_066_),
    .Y(_067_)
  );
  NAND _256_ (
    .A(valid2),
    .B(data_in2[7]),
    .Y(_068_)
  );
  NAND _257_ (
    .A(_125_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _258_ (
    .A(_067_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _259_ (
    .A(valid3),
    .B(_132_),
    .Y(_071_)
  );
  NAND _260_ (
    .A(reset_L),
    .B(_071_),
    .Y(_072_)
  );
  NOR _261_ (
    .A(_070_),
    .B(_072_),
    .Y(data_out_synth_mux[7])
  );
  NOR _262_ (
    .A(_119_),
    .B(_139_),
    .Y(_073_)
  );
  NAND _263_ (
    .A(valid1),
    .B(data_in1[8]),
    .Y(_074_)
  );
  NOT _264_ (
    .A(_074_),
    .Y(_075_)
  );
  NOR _265_ (
    .A(_073_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _266_ (
    .A(valid2),
    .B(_076_),
    .Y(_077_)
  );
  NAND _267_ (
    .A(valid2),
    .B(data_in2[8]),
    .Y(_078_)
  );
  NAND _268_ (
    .A(_125_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _269_ (
    .A(_077_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _270_ (
    .A(valid3),
    .B(_133_),
    .Y(_081_)
  );
  NAND _271_ (
    .A(reset_L),
    .B(_081_),
    .Y(_082_)
  );
  NOR _272_ (
    .A(_080_),
    .B(_082_),
    .Y(data_out_synth_mux[8])
  );
  NOR _273_ (
    .A(_120_),
    .B(_139_),
    .Y(_083_)
  );
  NAND _274_ (
    .A(valid1),
    .B(data_in1[9]),
    .Y(_084_)
  );
  NOT _275_ (
    .A(_084_),
    .Y(_085_)
  );
  NOR _276_ (
    .A(_083_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _277_ (
    .A(valid2),
    .B(_086_),
    .Y(_087_)
  );
  NAND _278_ (
    .A(valid2),
    .B(data_in2[9]),
    .Y(_088_)
  );
  NAND _279_ (
    .A(_125_),
    .B(_088_),
    .Y(_089_)
  );
  NOR _280_ (
    .A(_087_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _281_ (
    .A(valid3),
    .B(_134_),
    .Y(_091_)
  );
  NAND _282_ (
    .A(reset_L),
    .B(_091_),
    .Y(_092_)
  );
  NOR _283_ (
    .A(_090_),
    .B(_092_),
    .Y(data_out_synth_mux[9])
  );
  NOR _284_ (
    .A(_121_),
    .B(_139_),
    .Y(_093_)
  );
  NAND _285_ (
    .A(valid1),
    .B(data_in1[10]),
    .Y(_094_)
  );
  NOT _286_ (
    .A(_094_),
    .Y(_095_)
  );
  NOR _287_ (
    .A(_093_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _288_ (
    .A(valid2),
    .B(_096_),
    .Y(_097_)
  );
  NAND _289_ (
    .A(valid2),
    .B(data_in2[10]),
    .Y(_098_)
  );
  NAND _290_ (
    .A(_125_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _291_ (
    .A(_097_),
    .B(_099_),
    .Y(_100_)
  );
  NAND _292_ (
    .A(valid3),
    .B(_135_),
    .Y(_101_)
  );
  NAND _293_ (
    .A(reset_L),
    .B(_101_),
    .Y(_102_)
  );
  NOR _294_ (
    .A(_100_),
    .B(_102_),
    .Y(data_out_synth_mux[10])
  );
  NOR _295_ (
    .A(_122_),
    .B(_139_),
    .Y(_103_)
  );
  NAND _296_ (
    .A(valid1),
    .B(data_in1[11]),
    .Y(_104_)
  );
  NOT _297_ (
    .A(_104_),
    .Y(_105_)
  );
  NOR _298_ (
    .A(_103_),
    .B(_105_),
    .Y(_106_)
  );
  NOR _299_ (
    .A(valid2),
    .B(_106_),
    .Y(_107_)
  );
  NAND _300_ (
    .A(valid2),
    .B(data_in2[11]),
    .Y(_108_)
  );
  NAND _301_ (
    .A(_125_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _302_ (
    .A(_107_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _303_ (
    .A(valid3),
    .B(_136_),
    .Y(_111_)
  );
  NAND _304_ (
    .A(reset_L),
    .B(_111_),
    .Y(_112_)
  );
  NOR _305_ (
    .A(_110_),
    .B(_112_),
    .Y(data_out_synth_mux[11])
  );
endmodule
